### ISSUE TITLE
ValueError when calling datacube without arguments, --version, or --help

### ISSUE THREAD

**Issue by EHJ-52n** [opendatacube/datacube-core#1133]
### Expected behaviour

1. `datacube` prints help message because of missing parameters
2. `datacube --version` prints current version
3. `datacube --help` prints help message

### Actual behaviour

<details>
<summary>Error output</summary>

```
(.venv) $ datacube                                                                                                                                    12:29
Traceback (most recent call last):
  File "/home/user/odc-using-code/.venv/bin/datacube", line 5, in <module>
    from datacube.scripts.cli_app import cli
  File "/home/user/odc-using-code/.venv/lib/python3.9/site-packages/datacube/scripts/cli_app.py", line 8, in <module>
    from datacube.ui.click import cli
  File "/home/user/odc-using-code/.venv/lib/python3.9/site-packages/datacube/ui/click.py", line 173, in <module>
    def cli():
  File "/home/user/odc-using-code/.venv/lib/python3.9/site-packages/datacube/ui/click.py", line 49, in <lambda>
    return lambda x: f(g(x))
  File "/home/user/odc-using-code/.venv/lib/python3.9/site-packages/datacube/ui/click.py", line 49, in <lambda>
    return lambda x: f(g(x))
  File "/home/user/odc-using-code/.venv/lib/python3.9/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/home/user/odc-using-code/.venv/lib/python3.9/site-packages/click/core.py", line 2482, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/home/user/odc-using-code/.venv/lib/python3.9/site-packages/click/core.py", line 2108, in __init__
    raise ValueError(
ValueError: 'default' must be a list when 'multiple' is true.
```

</details>

### Steps to reproduce the behaviour

<details>
<summary>requirements.txt</summary>

```
affine==2.3.0
attrs==21.2.0
cachetools==4.2.2
certifi==2021.5.30
cftime==1.5.0
click==8.0.1
click-plugins==1.1.1
cligj==0.7.2
cloudpickle==1.6.0
dask==2021.6.2
distributed==2021.6.2
Fiona==1.8.20
fsspec==2021.6.1
geojson==2.5.0
geopandas==0.9.0
greenlet==1.1.0
HeapDict==1.0.1
jsonschema==3.2.0
lark-parser==0.11.3
locket==0.2.1
msgpack==1.0.2
munch==2.5.0
netCDF4==1.5.7
numpy==1.21.0
pandas==1.2.5
partd==1.2.0
pathlib==1.0.1
psutil==5.8.0
psycopg2-binary==2.9.1
pyparsing==2.4.7
pyproj==3.1.0
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2021.1
PyYAML==5.4.1
rasterio==1.2.6
rioxarray==0.4.2
scipy==1.7.0
Shapely==1.7.1
six==1.16.0
snuggs==1.4.7
sortedcontainers==2.4.0
SQLAlchemy==1.4.19
tblib==1.7.0
toolz==0.11.1
tornado==6.1
urllib3==1.26.5
xarray==0.18.2
zict==2.0.0
```

</details>

<details>
<summary>System Set-Up</summary>

```
$ python --version
Python 3.9.5
$ python -m venv --prompt odc-test .venv
$ source .venv/bin/activate
(odc-test) $ pip install -r requirements.txt
[...]
(odc-test) $ pip install --no-dependencies datacube[all]
(odc-test) $ rehash   <-- I am using zsh
(odc-test) $ datacube --help
```

</details>

### Environment information

* Which ``datacube --version`` are you using?
  * following pip: 1.8.3
 
<details>
<summary>pip list</summary>

```
Package          Version
---------------- ---------
affine           2.3.0
attrs            21.2.0
cachetools       4.2.2
certifi          2021.5.30
cftime           1.5.0
click            8.0.1
click-plugins    1.1.1
cligj            0.7.2
cloudpickle      1.6.0
dask             2021.6.2
datacube         1.8.3
distributed      2021.6.2
Fiona            1.8.20
fsspec           2021.6.1
geojson          2.5.0
geopandas        0.9.0
greenlet         1.1.0
HeapDict         1.0.1
jsonschema       3.2.0
lark-parser      0.11.3
locket           0.2.1
msgpack          1.0.2
munch            2.5.0
netCDF4          1.5.7
numpy            1.21.0
pandas           1.2.5
partd            1.2.0
pathlib          1.0.1
pip              20.3.4
pkg-resources    0.0.0
psutil           5.8.0
psycopg2-binary  2.9.1
pyparsing        2.4.7
pyproj           3.1.0
pyrsistent       0.17.3
python-dateutil  2.8.1
pytz             2021.1
PyYAML           5.4.1
rasterio         1.2.6
rioxarray        0.4.2
scipy            1.7.0
setuptools       44.1.1
Shapely          1.7.1
six              1.16.0
snuggs           1.4.7
sortedcontainers 2.4.0
SQLAlchemy       1.4.19
tblib            1.7.0
toolz            0.11.1
tornado          6.1
urllib3          1.26.5
xarray           0.18.2
zict             2.0.0
```
</details>

* What datacube deployment/enviornment are you running against?

I am working against a local test environment using a postgres database and local filestorage.

**Comment by EHJ-52n** [comment]
This error is caused by click > 7.1.2. Downgrading click solves the issue when using datacube 1.8.3. In addition, the development branch already contains a fix in https://github.com/opendatacube/datacube-core/commit/d5f76180575070f7bf5d24fc4eb919194602ad9f

Thanks to @Kirill888 for responding very fast in the according slack channel.
