### ISSUE TITLE
Datacube breaks geopandas s3 reading

### ISSUE THREAD

**Issue by MatthewJA** [opendatacube/datacube-core#1186]
### Expected behaviour
```
>>> import datacube, geopandas as gpd
>>> shp = "s3://dea-public-data/projects/WaterBodies/moree-test/AusWaterBodies_Moree.shp"
>>> gpd.read_file(shp)
[...a shapefile...]
```

### Actual behaviour
```
>>> import datacube, geopandas as gpd
>>> shp = "s3://dea-public-data/projects/WaterBodies/moree-test/AusWaterBodies_Moree.shp"
>>> gpd.read_file(shp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/env/lib/python3.6/site-packages/geopandas/io/file.py", line 129, in _read_file
    req = _urlopen(filename)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 549, in _open
    'unknown_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1395, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: s3>
```

Note that without the datacube import, this code works fine.

### Environment information

1.8.4.dev81+g80d466a2 on Sandbox

**Comment by Kirill888** [comment]
My guess it's because of this:

https://github.com/opendatacube/datacube-core/blob/3a49f78ead159da505cd78803d6710e7762b3a7e/datacube/utils/uris.py#L219-L238

@MatthewJA note that importing geopandas BEFORE importing datacube would allow you to keep using `.read_file`, so that's a work around. But it seems like an error in geopandas to be honest. It somehow decides to use normal http for s3 access

**Comment by Kirill888** [comment]
dodgy fix when import order can not be controlled is to do this before attempting to read s3 resources:

```python
gpd.io.file._VALID_URLS.discard("s3")
```

**Comment by Kirill888** [comment]
https://github.com/geopandas/geopandas/issues/2068

**Comment by MatthewJA** [comment]
Thanks for following this up with Geopandas!

**Comment by robbibt** [comment]
In a strange co-incidence, I just encountered this problem today, and can verify that it is still an issue.

**Comment by SpacemanPaul** [comment]
This issue is blocked on the geopandas side.
