### ISSUE TITLE
find datasets for multiple products with one query

### ISSUE THREAD

**Issue by valpesendorfer** [opendatacube/datacube-core#1196]
Is it possible to query datasets for two or more products with the same query parameters with one single query? Say the two products are Sentinel-2 A and Sentinel-2 B and I want to have datasets for both over the same area and time. 

_Note_:  I'm still running `datacube==1.8.3` so not sure if that's already possible in later releases.

### Expected behaviour

When specifying a list or tuple of products in `datacube.find_datasets` to get a list of datasets for all specified products that also match the query arguments.

If this feature is not supported, the query should raise a relevant exception.

### Actual behaviour

When using the `product` kwarg with a list, the query seems to return the results for the first product in the list. Would be better if it returns either results for all specified products or raises an exception.

When using a tuple,  the tuple is considered a single product which raises `ValueError: No products match search terms`. If this is not supported, would be better to raise an exception before any query is performed.

### Steps to reproduce the behaviour
```python

dc = Datacube()

# using a list returns all results for product_1
dc.find_datasets(product=["product_1", "product_2"])

# using a tuple raises a ValueError
dc.find_datasets(product=("product_1", "product_2"))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/datacube/api/core.py", line 331, in find_datasets
    return list(self.find_datasets_lazy(**search_terms))
  File "/usr/local/lib/python3.8/dist-packages/datacube/index/_datasets.py", line 510, in search
    for product, datasets in self._do_search_by_product(query,
  File "/usr/local/lib/python3.8/dist-packages/datacube/index/_datasets.py", line 635, in _do_search_by_product
    raise ValueError('No products match search terms: %r' % query)
ValueError: No products match search terms: {'product': ('product_1', 'product_2')}
```

### Environment information

* Which ``datacube --version`` are you using?

Open Data Cube core, version 1.8.3

* What datacube deployment/enviornment are you running against?

> NAME="Ubuntu"
> VERSION="20.04.1 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 20.04.1 LTS"
> VERSION_ID="20.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=focal
> UBUNTU_CODENAME=focal

> **Note:** Stale issues will be automatically closed after a period of six months with no activity. 
> To ensure critical issues are not closed, tag them with the Github `pinned` tag .

**Comment by Kirill888** [comment]
Pretty sure that

```
dss = dc.find_datasets(product=[p1, p2])
```
is equivalent to

```
dss = dc.find_datasets(product=p1, ...)+dc.find_datasets(product=p2, ...)
```

probably what's happening is that either
1. Typo in one of the product names
2. No datasets for product2 for tat query

If you make test enviornment with `datacube==1.8.5` and run the same test you might get a more informative error.

And yes only list was understood to mean "query multiple products", any other Iterable was not supported back then.
https://github.com/opendatacube/datacube-core/blob/16759a2d1a6e63899cc06cc92b7005df3c678b08/datacube/index/_products.py#L330
https://github.com/opendatacube/datacube-core/blob/16759a2d1a6e63899cc06cc92b7005df3c678b08/datacube/index/_products.py#L335-L336

see how it only checked for it being a list and not other kind of sequence

**Comment by Kirill888** [comment]
Actually this has not been fixed, only `product: List[str]` is understood to mean several products, error message for a single mistyped product was corrected, but multi-product queries are still "list only" in 1.8.5 version

**Comment by valpesendorfer** [comment]
thanks @Kirill888 - indeed the list does work. To test I was using the same product name (for inexplicable reasons) expecting the results to be the same as `dc.find_datasets(product=product) + dc.find_datasets(product=product)` wich it is not. Using two different products returns the result as expected.

Thanks for the help!
