### ISSUE TITLE
datacube-config database init fails silently on windows10

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#125]
```
[py35] dropdb.exe datacube

[py35] createdb datacube

[py35] C:\datacube\code\agdc-v2>datacube-config -vvv database init
Initialising database...
2016-04-19 17:04:03,881 INFO Ensuring user roles.
2016-04-19 17:04:03,886 DEBUG Role exists: agdc_user
2016-04-19 17:04:03,888 DEBUG Role exists: agdc_ingest
2016-04-19 17:04:03,890 DEBUG Role exists: agdc_manage
2016-04-19 17:04:03,892 DEBUG Role exists: agdc_admin
2016-04-19 17:04:03,897 INFO Creating schema.
2016-04-19 17:04:03,900 INFO Creating tables.
Traceback (most recent call last):
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
psycopg2.DataError: role "simon" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\simon\anaconda3\envs\py35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\simon\anaconda3\envs\py35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Simon\Anaconda3\envs\py35\Scripts\datacube-config.exe\__main__.py", line 9, in <module>
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\datacube\ui\click.py", line 114, in with_index
    return f(index, *args, **kwargs)
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\datacube\scripts\config_tool.py", line 54, in database_init
    with_permissions=init_users)
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\datacube\index\_api.py", line 50, in init_db
    is_new = self._db.init(with_permissions=with_permissions)
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\datacube\index\postgres\_api.py", line 149, in init
    return tables.ensure_db(self._engine, with_permissions=with_permissions)
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\datacube\index\postgres\tables\_core.py", line 76, in ensure_db
    c.execute('set role ' + db_user)
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\sqlalchemy\engine\base.py", line 906, in execute
    return self._execute_text(object, multiparams, params)
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\sqlalchemy\engine\base.py", line 1054, in _execute_text
    statement, parameters
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
    context)
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\sqlalchemy\util\compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\sqlalchemy\util\compat.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)
  File "c:\users\simon\anaconda3\envs\py35\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.DataError) role "simon" does not exist
 [SQL: 'set role Simon']
```

**Comment by simonaoliver** [comment]
#126

**Comment by jeremyh** [comment]
This may be a case-insensitivity bug on Windows. His username is 'Simon', but error messages are user 'simon'.

**Comment by simonaoliver** [comment]
That's pretty insensitive @jeremyh
