### ISSUE TITLE
Trouble running integration tests

### ISSUE THREAD

**Issue by marghb** [opendatacube/datacube-core#1419]
### Expected behaviour

I expect all tests should pass.

### Actual behaviour

while running `./check-code.sh integration_tests`
Resulted in:

```
 File "/home/tebaka/anaconda3/lib/python3.9/site-packages/astroid/decorators.py", line 136, in raise_if_nothing_inferred
    yield next(generator)
RecursionError: maximum recursion depth exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tebaka/anaconda3/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 727, in _check_file
    check_astroid_module(ast_node)
  File "/home/tebaka/anaconda3/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 926, in check_astroid_module
    retval = self._check_astroid_module(
  File "/home/tebaka/anaconda3/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 976, in _check_astroid_module
    walker.walk(node)
  File "/home/tebaka/anaconda3/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  File "/home/tebaka/anaconda3/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/home/tebaka/anaconda3/lib/python3.9/site-packages/pylint/checkers/imports.py", line 487, in visit_importfrom
    imported_module = self._get_imported_module(node, basename)
  File "/home/tebaka/anaconda3/lib/python3.9/site-packages/pylint/checkers/imports.py", line 788, in _get_imported_module
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tebaka/anaconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/tebaka/anaconda3/lib/python3.9/site-packages/pylint/lint/parallel.py", line 72, in _worker_check_single_file
    _worker_linter.check_single_file_item(file_item)
  File "/home/tebaka/anaconda3/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 673, in check_single_file_item
    self._check_file(self.get_ast, check_astroid_module, file)
  File "/home/tebaka/anaconda3/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 729, in _check_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tebaka/anaconda3/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/home/tebaka/anaconda3/lib/python3.9/site-packages/pylint/__init__.py", line 25, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/home/tebaka/anaconda3/lib/python3.9/site-packages/pylint/lint/run.py", line 207, in __init__
    linter.check(args)
  File "/home/tebaka/anaconda3/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 650, in check
    check_parallel(
  File "/home/tebaka/anaconda3/lib/python3.9/site-packages/pylint/lint/parallel.py", line 152, in check_parallel
    for (
  File "/home/tebaka/anaconda3/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
astroid.exceptions.AstroidError
```

### Steps to reproduce the behaviour

follow steps in https://datacube-core.readthedocs.io/en/latest/installation/setup/ubuntu.html

### Environment information

latest datacube version
Ubuntu 22.10

**Comment by omad** [comment]
Hi _marghb_, 

I've tried and can't reproduce your error. From the stack trace, it looks like something has gone wrong with the installation of `pylint`, which is a code quality tool we use. 

The solution would be to recreate the environment you're running the tests in.

If it continues to happen, we need more information about the version of pylint `pylint --version` and the conda environment.
