### ISSUE TITLE
S2 ingest fails

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#147]
Indexing works fine but ingest fails with the following output:

root@8cae991b512b:/shared/ingester# datacube ingest -c s2amsil1c_albers_10.yaml
2016-07-12 13:21:11,109 ERROR Task failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/datacube-1.1.3+18.g657729b-py2.7.egg/datacube/scripts/ingest.py", line 227, in process_tasks
    datasets = executor.result(result)
  File "/usr/local/lib/python2.7/dist-packages/datacube-1.1.3+18.g657729b-py2.7.egg/datacube/executor.py", line 35, in result
    return func(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/datacube-1.1.3+18.g657729b-py2.7.egg/datacube/scripts/ingest.py", line 207, in ingest_work
    datasets = xr_apply(sources, _make_dataset, dtype='O')
  File "/usr/local/lib/python2.7/dist-packages/datacube-1.1.3+18.g657729b-py2.7.egg/datacube/model/utils.py", line 167, in xr_apply
    v = func(index, entry)
  File "/usr/local/lib/python2.7/dist-packages/datacube-1.1.3+18.g657729b-py2.7.egg/datacube/scripts/ingest.py", line 197, in _make_dataset
    assert len(sources) == 1
AssertionError

**Comment by v0lat1le** [comment]
The overlap in the granules is causing it.
The assert is there to catch errors in Landsat data which is not meant to have overlaps. It has caught several so far... I'll need to think of a generic solution for this...

**Comment by simonaoliver** [comment]
Maybe an --allow-overlap --average switch for data with same date stamp, taking the first by default

**Comment by v0lat1le** [comment]
try adding `fuse_data: copy` into config now

**Comment by fcastel** [comment]
The ingestion was successfull for Sentinel-2 data with the additional configuration element, thank you!

Just one question, what are the others possible  values of the fuse_data property ?

**Comment by v0lat1le** [comment]
No other values for now.
`copy` fuses datasets by filling in no data values of one by values from the other ones. The order in which datasets are considered is not defined
