### ISSUE TITLE
Trouble Ingesting USGS Landsat and MODIS data 

### ISSUE THREAD

**Issue by robeson1010** [opendatacube/datacube-core#246]
When I build a datacube on my server, I have already install the  datacube and init the database. How can I index the landsat data like  LC80090452014008LGN00 with tif file. 
I tried use the ‘usgslsprepare.py’ 

> ` python datacube-core/utils/usgslsprepare.py /home/tensorx/data/datacube/landsat/*/`

it was wrong

```
2017-06-19 15:39:57,274 INFO Processing /home/tensorx/data/datacube/landsat/LC80090452014008LGN00
Traceback (most recent call last):
  File "datacube-core/utils/usgslsprepare.py", line 265, in <module>
    main()
  File "/home/tensorx/miniconda2/envs/datacube3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/tensorx/miniconda2/envs/datacube3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/tensorx/miniconda2/envs/datacube3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tensorx/miniconda2/envs/datacube3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "datacube-core/utils/usgslsprepare.py", line 256, in main
    documents = prepare_datasets(path)
  File "datacube-core/utils/usgslsprepare.py", line 241, in prepare_datasets
    nbar = prep_dataset(fields, nbar_path)
  File "datacube-core/utils/usgslsprepare.py", line 163, in prep_dataset
    with open(os.path.join(str(path), metafile)) as f:
UnboundLocalError: local variable 'metafile' referenced before assignment
```
How to fix it？

**Comment by Lunasunsea** [comment]
I have also met this problem,have you fix it?

**Comment by harshurampur** [comment]
@Lunasunsea and @robeson1010 Could you please provide me the link where you have downloaded the data from or just the .xml file that you are referring to.. Its hard to figure out the pre-collection data for .xml file, as they all have been updated to 'mtl.txt'. Thanks

**Comment by amruthkiran94** [comment]
@robeson1010  @Lunasunsea @harshurampur  Any updates on this issue? I'm facing the same problem.
I'll attach the documents required. Data is a Landsat 5 scene.
[LT05_L1TP_145039_20111109_20161005_01_T1_MTL.txt](https://github.com/opendatacube/datacube-core/files/1231948/LT05_L1TP_145039_20111109_20161005_01_T1_MTL.txt)

**Comment by harshurampur** [comment]
@amruthkiran94 The file you are trying to index is Collection 1 Landsat 5 MTL format, but the preparescript 'usgslsprepare.py' only supports Pre-Collection data and the file has to be .xml format.

**Comment by amruthkiran94** [comment]
Thank you @harshurampur  for your prompt reply! The Landsat 5 Collection 1 data set does not provide a .xml metadata, only a .mtl file. How would I be able to use a Landsat 5 imagery with mtl metadata? Any other scripts? I'm using the https://github.com/opendatacube/datacube-core/tree/develop/utils as a reference.

**Comment by harshurampur** [comment]
@amruthkiran94 USGS has phased out the `.xml` format for all the Collection 1 data. There is no other script to index `MTL` metadata for Collection 1. We are working on it.
Sincere apologies.

**Comment by amruthkiran94** [comment]
@harshurampur  There is a small workaround I just figured out. USGS data when downloaded via the "download options" button links to a preprocessed data and its contents ~200mb does not contain the .xml file. The same scene when ordered via the "order scene" button and downloaded after processing contains the .xml file and successfully is read by the script at https://github.com/opendatacube/datacube-core/blob/develop/utils/usgs_ls_ard_prepare.py 
I am attaching a Zip file with a screenshot of the process and the meta data YAML file generated.

[Landsat 5 _Github_Comment.zip](https://github.com/opendatacube/datacube-core/files/1233601/Landsat.5._Github_Comment.zip)
 
Edit: Also, which script should I consider to create the Metadata-datacube.yaml for Level 1 Landsat 5 datasets? I get a data set inconsistency error while indexing. (This is after the above workaround). The Zip file contains the error screenshot and the generated metadata-datacube .yaml which is causing the error. Thanks!!
[Landsat_5_GitHub_Comment_2.zip](https://github.com/opendatacube/datacube-core/files/1234342/Landsat_5_GitHub_Comment_2.zip)

Edit_2: I found the solution to the above problem, use https://github.com/ceos-seo/agdc-v2/tree/master/ingest/prepare_scripts/landsat_collection/usgs_ls_ard_prepare.py to create the 'metadata-datacube.yaml' or similar file.  If a "No matching product error", add the product "ls5_collections_sr_scene" into the database and try indexing again. Ingestion  can be done using the "ls5_collections_sr_general.yaml" file.

**Comment by harshurampur** [comment]
@amruthkiran94 That's Great! I am sure you will be able to do the same with MTL soon. Thanks

**Comment by harshurampur** [comment]
@amruthkiran94 You mentioned "order scene" in previous comment that you were able to download .xml file through this, I followed the same steps as you mentioned via the "order scene" and after processing when i downloaded the data, there was no xml file in it. 
I am referring to Earth explorer, landsat7 pre-collection level 1. Did you followed the same?

**Comment by amruthkiran94** [comment]
@harshurampur  I have carried out the steps as you have done for both Landsat 5 and Landsat 7 **Collection 1 data**, not the Pre-Collection datasets. Attaching files for reference.
The Pre-Collection data would be discontinued, 

> " Changes to Pre-Collection datasets: Effective April 30, 2017, newly-acquired Landsat 7 ETM+ and Landsat 8 OLI/TIRS scenes are being processed into the Landsat Collection 1 inventory only; Landsat Pre-Collection inventory is no longer being populated with newly-acquired data.
>  
> Users downloading Landsat Pre-Collection data may experience longer than expected download times.
>  
> The Landsat Pre-Collection inventory will no longer be available after October 1, 2017. Users are strongly encouraged to use only Landsat Collection 1 in their applications."


The files below are, the XML, MTL and generated Metadata.YAML files of LS5 and LS7.
[Comments_1.zip](https://github.com/opendatacube/datacube-core/files/1237729/Comments_1.zip)

**Comment by Lunasunsea** [comment]
Thanks a lot！But when I use the data and the script you mentioned，I met the problem：
“Traceback (most recent call last):
  File "C:\Python27\datacube-core-develop\utils\USGS_precollection_oldscripts\usgs_ls_ard_prepare.py", line 270, in <module>
    main()
  File "C:\Users\Administrator\Miniconda2\envs\cubeenv\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\Miniconda2\envs\cubeenv\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\Miniconda2\envs\cubeenv\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\Miniconda2\envs\cubeenv\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Python27\datacube-core-develop\utils\USGS_precollection_oldscripts\usgs_ls_ard_prepare.py", line 261, in main
    documents = prepare_datasets(path)
  File "C:\Python27\datacube-core-develop\utils\USGS_precollection_oldscripts\usgs_ls_ard_prepare.py", line 245, in prepare_datasets
    nbar = prep_dataset(fields, nbar_path)
  File "C:\Python27\datacube-core-develop\utils\USGS_precollection_oldscripts\usgs_ls_ard_prepare.py", line 187, in prep_dataset
    projdict['valid_data'] = safe_valid_region(images_list)
  File "C:\Python27\datacube-core-develop\utils\USGS_precollection_oldscripts\usgs_ls_ard_prepare.py", line 41, in safe_valid_region
    return valid_region(images, mask_value)
  File "C:\Python27\datacube-core-develop\utils\USGS_precollection_oldscripts\usgs_ls_ard_prepare.py", line 64, in valid_region
    shapes = rasterio.features.shapes(mask.astype('uint8'), mask=mask)
AttributeError: 'NoneType' object has no attribute 'astype'”
Have you ever met this problem? How to fix it? Thanks a lot!

**Comment by amruthkiran94** [comment]
@Lunasunsea This usually occurs due to the mismatch of the script and the data set used. Try using the "usgslsprepare" script.
 The "usgs_ls_ard_prepare" script is for ARD or Analysis Ready Data only.

**Comment by Lunasunsea** [comment]
Thank you very much!

**Comment by Lunasunsea** [comment]
Have you ever tried to ingest the MODIS product?When I am trying this,it appears:

F:\enviroment>datacube ingest -c C:\Python27\datacube-core-develop\docs\config_samples\ingester\mcd43a1_sinusoidal.yaml
Traceback (most recent call last):
  File "C:\Python27\Scripts\datacube-script.py", line 11, in <module>
    load_entry_point('datacube==0+unknown', 'console_scripts', 'datacube')()
  File "C:\Python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Python27\lib\site-packages\datacube-0+unknown-py2.7.egg\datacube\ui\click.py", line 208, in with_driver_manager
    return f(driver_manager, *args, **kwargs)
  File "C:\Python27\lib\site-packages\datacube-0+unknown-py2.7.egg\datacube\scripts\ingest.py", line 376, in ingest_cmd
    source_type, output_type = make_output_type(driver_manager, config)
  File "C:\Python27\lib\site-packages\datacube-0+unknown-py2.7.egg\datacube\scripts\ingest.py", line 157, in make_output_type
    output_type = morph_dataset_type(source_type, config, driver_manager.driver.format)
  File "C:\Python27\lib\site-packages\datacube-0+unknown-py2.7.egg\datacube\scripts\ingest.py", line 88, in morph_dataset_type
    for spec in config['measurements']]
KeyError: 'BRDF_Albedo_Parameters_Band1'
Do you konw the reason?
Thank you very much!

**Comment by harshurampur** [comment]
@Lunasunsea Have you tried to ingest using other modis files available in the /ingester folder. If so, do you get the same error?

**Comment by amruthkiran94** [comment]
@harshurampur The script for the USGS Prepare- MTL format is working well. Thank you. :) 
How do i go about ingesting any LS'x' data now that the prepare script is modified?
Will the original AGDC ingestion scripts be compatible?

**Comment by harshurampur** [comment]
@amruthkiran94 There aren't any ingest scripts available for the landsat8/7/5 for collection 1 data. I will  update ingestion config file as soon as possible. Meanwhile, if you are keen in creating an ingestion script for the indexed data please follow this link below: 
http://datacube-core.readthedocs.io/en/stable/ops/config.html#ingestion-config

**Comment by ashu6397** [comment]
@Lunasunsea were you able to resolve the issue in ingesting the "mcd43a1_sinusoidal.yaml" file?

**Comment by alexgleith** [comment]
Closing this issue. If there are any remaining issues with data indexing or preparation scripts, please check against the scripts in this new repository: https://github.com/opendatacube/datacube-dataset-config
