### ISSUE TITLE
Metadata script for Sentinel 1

### ISSUE THREAD

**Issue by fxstempfel** [opendatacube/datacube-core#405]
Hi,
This issue is related to #164 but the scripts changed since so I'm opening a new one.
I'm trying to ingest Sentinel 1 data that I exported with SNAP from SAFE format to BEAM DIMAP. I got a .dim file and a .data folder which contains .img and .hdr files. I've put both the .dim file and the .data folder into a folder and I've run the Python script as follows:
`python prep_s1a.py /datacube/original_data
S1A_IW_SLC__1SDV_20180303T174720_20180303T174748_020854_023C45_BBA4/`

### Expected behaviour
The script should generate a metadata YAML file.

### Actual behaviour
I got the following error:
> Traceback (most recent call last):
  File "agdc-v2/ingest/prepare_scripts/sentinel_1/prep_s1a.py", line 160, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "agdc-v2/ingest/prepare_scripts/sentinel_1/prep_s1a.py", line 151, in main
    metadata = prep_dataset(path)
  File "agdc-v2/ingest/prepare_scripts/sentinel_1/prep_s1a.py", line 105, in prep_dataset
    projection, extent = get_geometry('/'.join([str(path), images['vv']['path']]))
  File "agdc-v2/ingest/prepare_scripts/sentinel_1/prep_s1a.py", line 30, in get_geometry
    crs = str(str(getattr(img, 'crs_wkt', None) or img.crs.wkt))
AttributeError: 'NoneType' object has no attribute 'wkt'

because img.crs is None. 

Has someone tried to use this Python script yet and am I doing something wrong?

Best regards,
FX

**Comment by omad** [comment]
Thanks for the report FX, I haven't used that prepare script, so I'm not sure how recently it was tested.

Hopefully @caffeine-potent or @AMA-AC can chime in with more of an idea.
