### ISSUE TITLE
Core accepts a broken product definition

### ISSUE THREAD

**Issue by tina5870** [opendatacube/datacube-core#411]
An error was thrown after adding this product, but on retry it said successfully added.
[ard-interoperability_bk2.yaml.gz](https://github.com/opendatacube/datacube-core/files/1892782/ard-interoperability_bk2.yaml.gz)

Now we can't run `datacube product list`, as it always dies with the same error:

```
Traceback (most recent call last):
  File "/g/data/v10/public/modules/agdc-py3/1.5.4/bin/datacube", line 11, in <module>
    sys.exit(cli())
  File "/g/data/v10/public/modules/agdc-py3-env/20171214/envs/agdc/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/g/data/v10/public/modules/agdc-py3-env/20171214/envs/agdc/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/g/data/v10/public/modules/agdc-py3-env/20171214/envs/agdc/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/g/data/v10/public/modules/agdc-py3-env/20171214/envs/agdc/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/g/data/v10/public/modules/agdc-py3-env/20171214/envs/agdc/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/g/data/v10/public/modules/agdc-py3-env/20171214/envs/agdc/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/g/data/v10/public/modules/agdc-py3/1.5.4/lib/python3.6/site-packages/datacube/ui/click.py", line 193, in with_index
    return f(index, *args, **kwargs)
  File "/g/data/v10/public/modules/agdc-py3/1.5.4/lib/python3.6/site-packages/datacube/scripts/product.py", line 116, in list_products
    products = dc.list_products()
  File "/g/data/v10/public/modules/agdc-py3/1.5.4/lib/python3.6/site-packages/datacube/api/core.py", line 95, in list_products
    rows = [datatset_type_to_row(dataset_type) for dataset_type in self.index.products.get_all()]
  File "/g/data/v10/public/modules/agdc-py3/1.5.4/lib/python3.6/site-packages/datacube/api/core.py", line 95, in <listcomp>
    rows = [datatset_type_to_row(dataset_type) for dataset_type in self.index.products.get_all()]
  File "/g/data/v10/public/modules/agdc-py3/1.5.4/lib/python3.6/site-packages/datacube/api/core.py", line 609, in datatset_type_to_row
    row.update(dt.fields)
  File "/g/data/v10/public/modules/agdc-py3/1.5.4/lib/python3.6/site-packages/datacube/model/__init__.py", line 396, in fields
    return self.metadata_type.dataset_reader(self.metadata_doc).fields
  File "/g/data/v10/public/modules/agdc-py3/1.5.4/lib/python3.6/site-packages/datacube/utils/__init__.py", line 645, in fields
    fields.update(self.search_fields)
  File "/g/data/v10/public/modules/agdc-py3/1.5.4/lib/python3.6/site-packages/datacube/utils/__init__.py", line 654, in search_fields
    fields[name] = field.extract(self._doc)
  File "/g/data/v10/public/modules/agdc-py3/1.5.4/lib/python3.6/site-packages/datacube/index/postgres/_fields.py", line 215, in extract
    return self._extract_offset_value(document, self.offset, self.aggregation.calc)
  File "/g/data/v10/public/modules/agdc-py3/1.5.4/lib/python3.6/site-packages/datacube/index/postgres/_fields.py", line 174, in _extract_offset_value
    values = [self.parse_value(v) for v in values if v is not None]
  File "/g/data/v10/public/modules/agdc-py3/1.5.4/lib/python3.6/site-packages/datacube/index/postgres/_fields.py", line 174, in <listcomp>
    values = [self.parse_value(v) for v in values if v is not None]
  File "/g/data/v10/public/modules/agdc-py3/1.5.4/lib/python3.6/site-packages/datacube/index/postgres/_fields.py", line 173, in <genexpr>
    values = (get_doc_offset_safe(offset, doc) for offset in doc_offsets)
  File "/g/data/v10/public/modules/agdc-py3/1.5.4/lib/python3.6/site-packages/datacube/utils/__init__.py", line 140, in get_doc_offset_safe
    return get_doc_offset(offset, document)
  File "/g/data/v10/public/modules/agdc-py3/1.5.4/lib/python3.6/site-packages/datacube/utils/__init__.py", line 124, in get_doc_offset
    value = value[key]
TypeError: string indices must be integers
```

Modules:
```
[tty547@vdi-n4 ARD_interoperability]$ datacube --version
Open Data Cube core, version 1.5.4
[tty547@vdi-n4 ARD_interoperability]$ module list
Currently Loaded Modulefiles:
  1) pbs                      2) /agdc-py3-env/20171214   3) /agdc-py3/1.5.4          4) /agdc-py3-prod/1.5.4
[tty547@vdi-n4 ARD_interoperability]$ 
```

**Comment by uchchwhash** [comment]
Hi Tina,
Could you please check if the following works?
In the `metadata` section, please change
```yaml
    platform: LANDSAT_5
    instrument: TM
```
to
```yaml
    platform:
        code:  LANDSAT_5
    instrument:
        name: TM
```
and run a
```bash
datacube product update --allow-unsafe ard-interoperability_bk2.yaml
```
and let us know what happened?

**Comment by uchchwhash** [comment]
Resolved.
