### ISSUE TITLE
datacube product list with tab option

### ISSUE THREAD

**Issue by harshurampur** [opendatacube/datacube-core#623]
Datacube product list defaults to yaml output 
there is an option to change to `tab` but getting errors while choosing the `tab` option 
```Traceback (most recent call last):
  File "/home/harshu/miniconda/envs/cubenv/bin/datacube", line 11, in <module>
    load_entry_point('datacube==1.6.1', 'console_scripts', 'datacube')()
  File "/home/harshu/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/harshu/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/harshu/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harshu/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harshu/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harshu/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/harshu/.local/lib/python3.6/site-packages/datacube/ui/click.py", line 192, in new_func
    return f(parsed_config, *args, **kwargs)
  File "/home/harshu/.local/lib/python3.6/site-packages/datacube/ui/click.py", line 220, in with_index
    return f(index, *args, **kwargs)
  File "/home/harshu/.local/lib/python3.6/site-packages/datacube/ui/click.py", line 244, in with_datacube
    return f(Datacube(index=index), *args, **kwargs)
  File "/home/harshu/.local/lib/python3.6/site-packages/datacube/scripts/product.py", line 186, in list_products
    LIST_OUTPUT_WRITERS[f](build_product_list(dc.index))
  File "/home/harshu/.local/lib/python3.6/site-packages/datacube/scripts/product.py", line 168, in _write_tab
    justify='left'))
  File "/home/harshu/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 1970, in to_string
    show_dimensions=show_dimensions)
  File "/home/harshu/.local/lib/python3.6/site-packages/pandas/io/formats/format.py", line 428, in __init__
    self.frame = self.frame[self.columns]
  File "/home/harshu/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2682, in __getitem__
    return self._getitem_array(key)
  File "/home/harshu/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2726, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/home/harshu/.local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1327, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: "Index(['ancillary_quality', 'gqa_abs_iterative_mean_xy', 'gqa_ref_source',\n       'sat_path', 'gqa_iterative_stddev_xy', 'sat_row', 'orbit', 'gqa',\n       'gqa_abs_xy'],\n      dtype='object') not in index"
```

### Environment information

* Which ``datacube --version`` are you using?

Using `datacube 1.6.1`

**Comment by Kirill888** [comment]
@harshurampur  seems to be data dependant, running on nci `datacube product list -f tab` succeeds. What environment is this in?

**Comment by harshurampur** [comment]
I am working in virtualbox with conda environment.

**Comment by Kirill888** [comment]
Problem is here:

https://github.com/opendatacube/datacube-core/blob/c4595b91387011d4deec3c2d63f88e9e9aa01573/datacube/scripts/product.py#L144-L149

There is a hard-coded set of "columns", but not all products have all of them set, in your case these are missing:

```python
['ancillary_quality', 'gqa_abs_iterative_mean_xy', 'gqa_ref_source',
'sat_path', 'gqa_iterative_stddev_xy', 'sat_row', 
'orbit', 'gqa', 'gqa_abs_xy']
```

columns should be pruned to only include those that are present in the dataframe.

**Comment by harshurampur** [comment]
Thanks @Kirill888 . Yes they are all missing in the data I have indexed especially the `nidem` and `item`.
