### ISSUE TITLE
datacube-config database init fails

### ISSUE THREAD

**Issue by ama-jharrison** [opendatacube/datacube-core#77]
When running "datacube-config -v database init", the following error occurs:
`Traceback (most recent call last):
  File "/home/localuser/anaconda3/bin/datacube-config", line 9, in <module>
    load_entry_point('datacube==0.0.0+864.gd46179a', 'console_scripts', 'datacube-config')()
  File "/home/localuser/anaconda3/lib/python3.5/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/localuser/anaconda3/lib/python3.5/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/localuser/anaconda3/lib/python3.5/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/localuser/anaconda3/lib/python3.5/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/localuser/anaconda3/lib/python3.5/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/localuser/anaconda3/lib/python3.5/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/localuser/anaconda3/lib/python3.5/site-packages/datacube-0.0.0+864.gd46179a-py3.5.egg/datacube/ui/click.py", line 107, in new_func
    index = index_connect(click.get_current_context().obj['config_file'])
AttributeError: module 'click' has no attribute 'get_current_context'`
Our current datacube configuration file is:

> [Data Cube]
> db_hostname:
> db_database: datacube
> 
> db_username: USER HERE
> db_password: PASSWORD HERE
> 
> [locations]
> eotiles: file:///tilestore/eotiles
> v1tiles: file:///tilestore/data2/rs0/tiles/EPSG4326_deg1_0.00025pixel/

This is running in python 3.5.1 on Ubuntu 14.04

**Comment by omad** [comment]
Hiya, looks like an old version of the `click` python package. Try:

```
pip install --upgrade click
```

We still need to work out minimum versions and update the package dependencies appropriately.
