### ISSUE TITLE
datacube-config database init fails with python 3.5.1 on Ubuntu 14.04 - minimum version of click?

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#78]
I'm running into an error when running the command "datacube-config database init" or "datacube-config check" I get an error 
"File "/home/localuser/agdc-v2/datacube/ui/click.py", line 97, in new_func
    config_ = click.get_current_context().obj['config_file']
AttributeError: module 'click' has no attribute 'get_current_context'"

I'm currently running this off python 3.5.1 with from an anaconda distribution on Ubuntu 14.04. The commit pulled is d46179a from the develop branch. Is there any known issues with using this command to initialize the database?

When running "datacube-config -v database init", the following error occurs:
Traceback (most recent call last):
File "/home/localuser/anaconda3/bin/datacube-config", line 9, in <module>
load_entry_point('datacube==0.0.0+864.gd46179a', 'console_scripts', 'datacube-config')()
File "/home/localuser/anaconda3/lib/python3.5/site-packages/click/core.py", line 664, in **call**
return self.main(_args, *_kwargs)
File "/home/localuser/anaconda3/lib/python3.5/site-packages/click/core.py", line 644, in main
rv = self.invoke(ctx)
File "/home/localuser/anaconda3/lib/python3.5/site-packages/click/core.py", line 991, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/localuser/anaconda3/lib/python3.5/site-packages/click/core.py", line 991, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/localuser/anaconda3/lib/python3.5/site-packages/click/core.py", line 837, in invoke
return ctx.invoke(self.callback, *_ctx.params)
File "/home/localuser/anaconda3/lib/python3.5/site-packages/click/core.py", line 464, in invoke
return callback(_args, **kwargs)
File "/home/localuser/anaconda3/lib/python3.5/site-packages/datacube-0.0.0+864.gd46179a-py3.5.egg/datacube/ui/click.py", line 107, in new_func
index = index_connect(click.get_current_context().obj['config_file'])
AttributeError: module 'click' has no attribute 'get_current_context'
Our current datacube configuration file is:
[Data Cube]
db_hostname:
db_database: datacube
db_username: USER HERE
db_password: PASSWORD HERE
[locations]
eotiles: file:///tilestore/eotiles
v1tiles: file:///tilestore/data2/rs0/tiles/EPSG4326_deg1_0.00025pixel/
This is running in python 3.5.1 on Ubuntu 14.04

**Comment by omad** [comment]
This is the same issue as #77, closing.
