### ISSUE TITLE
KeyError: 'latitude' when working with netCDF product

### ISSUE THREAD

**Issue by jankovicgd** [opendatacube/datacube-core#815]
I am trying to provide a custom netcdf file with ODC. The indexing works but then working with it throws errors. The file is CF compliant, tested with an online compliance check. Tried also with `x` and `y` in the dataset yml. Is this related to https://github.com/opendatacube/datacube-core/issues/567?

### Expected behaviour
Retrieve products and load data.

### Actual behaviour

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/datacube-1.7rc1+3.gd3f447fa.dirty-py3.6.egg/datacube/api/core.py", line 93, in list_products
    rows = [product.to_dict() for product in self.index.products.get_all()]
  File "/usr/local/lib/python3.6/dist-packages/datacube-1.7rc1+3.gd3f447fa.dirty-py3.6.egg/datacube/api/core.py", line 93, in <listcomp>
    rows = [product.to_dict() for product in self.index.products.get_all()]
  File "/usr/local/lib/python3.6/dist-packages/datacube-1.7rc1+3.gd3f447fa.dirty-py3.6.egg/datacube/model/__init__.py", line 510, in to_dict
    if self.grid_spec is not None:
  File "/usr/local/lib/python3.6/dist-packages/datacube-1.7rc1+3.gd3f447fa.dirty-py3.6.egg/datacube/utils/py.py", line 58, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.6/dist-packages/datacube-1.7rc1+3.gd3f447fa.dirty-py3.6.egg/datacube/model/__init__.py", line 471, in grid_spec
    for name in ('tile_size', 'resolution', 'origin')}
  File "/usr/local/lib/python3.6/dist-packages/datacube-1.7rc1+3.gd3f447fa.dirty-py3.6.egg/datacube/model/__init__.py", line 471, in <dictcomp>
    for name in ('tile_size', 'resolution', 'origin')}
  File "/usr/local/lib/python3.6/dist-packages/datacube-1.7rc1+3.gd3f447fa.dirty-py3.6.egg/datacube/model/__init__.py", line 468, in extract_point
    return None if xx is None else tuple(xx[dim] for dim in crs.dimensions)
  File "/usr/local/lib/python3.6/dist-packages/datacube-1.7rc1+3.gd3f447fa.dirty-py3.6.egg/datacube/model/__init__.py", line 468, in <genexpr>
    return None if xx is None else tuple(xx[dim] for dim in crs.dimensions)
KeyError: 'latitude'
```

### Steps to reproduce the behaviour

```python
import datacube
dc = datacube.Datacube(app='test')
dc.list_products() # this function throws the above error
dc.load() # this function also throws above error when loading data
```

```yml
name: Name of product
description:Description
metadata_type: eo

storage:
  crs: EPSG:4326
  resolution:
    lat: 0.001057547317402
    lon: -0.000732880028590

metadata:
  format: { name: netCDF }
  instrument: { name: NONE }
  platform: { code: NONE }
  product_type: DEFORMATION

measurements:
  - name: deformation_up_down
    aliases: [band_1, band_01, Band1, Band_1]
    units: m
    dtype: float32
    nodata: 0
```

```yml
creation_dt: "2019-11-14T16:35:00.000000"
extent:
  center_dt: "2018-05-10T12:00:00"
  coord:
    ll:
      lat: 47.61735893230016
      lon: 15.808095493919424
    lr:
      lat: 47.61735893230016
      lon: 16.7461399644546
    ul:
      lat: 48.4784929658932
      lon: 15.808095493919424
    ur:
      lat: 48.4784929658932
      lon: 16.7461399644546
  from_dt: "2017-02-23T00:00:00"
  to_dt: "2019-07-25T00:00:00"
format:
  name: netCDF
grid_spatial:
  projection:
    geo_ref_points:
      ll:
        longitude: 15.808095493919424
        latitude: 47.61735893230016
      lr:
        longitude: 16.7461399644546
        latitude: 47.61735893230016
      ul:
        longitude: 15.808095493919424
        latitude: 48.4784929658932
      ur:
        longitude: 16.7461399644546
        latitude: 48.4784929658932
    spatial_reference: EPSG:4326
image:
  bands:
    deformation_up_down:
      layer: 1
      path: /path/to/netcdf.nc
instrument:
  name: NONE
name: Name
id: ddab18ae-06ef-11ea-8d71-362b9e155667
platform:
  code: NONE
product_format: "{SAFE_COMPACT}"
product_type: DEFORMATION
```

Thanks for your help.

### Environment information

* Which ``datacube --version`` are you using?
Open Data Cube core, version 1.7rc1+3.gd3f447fa.dirty.
* What datacube deployment/enviornment are you running against?
Running locally in docker.

**Comment by Kirill888** [comment]
@jankovicgd datacube support for `EPSG:4326` is kinda broken right now, you already mentioned #567 but there is also #556. For your specific case work around is:

1. Use `latitude`, `longitude` in the product spec `storage.resolution.{latitude|longitude}` (you use `lat`, `lon`
2. But in the dataset use `x,y` names: `grid_spatial.projection.geo_ref_points.{ll|lr|ur|ul}.{x|y}`

It's annoying and broken, but if you want to have it working "right now", this is what you have to do.

**Comment by jankovicgd** [comment]
Thanks for the reply, I will try it out.

**Comment by jankovicgd** [comment]
This solved my initial problem but now I seem to get a new error with the `Datacube.load()` function. I got the same error with some different datasets as well. Tried https://github.com/opendatacube/datacube-core/issues/421 but unfortunately it didn't work. The original issue can be closed though but I might need some help here too.

```
Error opening source dataset: netCDF:"/home/nikola/Data/SULAMOSA/SD022_sbas_short.nc":None
Traceback (most recent call last):
  File "rasterio/_base.pyx", line 213, in rasterio._base.DatasetBase.__init__
  File "rasterio/_shim.pyx", line 64, in rasterio._shim.open_dataset
  File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: netCDF:"/home/nikola/Data/SULAMOSA/SD022_sbas_short.nc":None: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/datacube-1.7rc1+3.gd3f447fa.dirty-py3.6.egg/datacube/api/core.py", line 316, in load
    **legacy_args)
  File "/usr/local/lib/python3.6/dist-packages/datacube-1.7rc1+3.gd3f447fa.dirty-py3.6.egg/datacube/api/core.py", line 610, in load_data
    progress_cbk=progress_cbk)
  File "/usr/local/lib/python3.6/dist-packages/datacube-1.7rc1+3.gd3f447fa.dirty-py3.6.egg/datacube/api/core.py", line 515, in _xr_load
    progress_cbk=_cbk)
  File "/usr/local/lib/python3.6/dist-packages/datacube-1.7rc1+3.gd3f447fa.dirty-py3.6.egg/datacube/api/core.py", line 732, in _fuse_measurement
    progress_cbk=progress_cbk)
  File "/usr/local/lib/python3.6/dist-packages/datacube-1.7rc1+3.gd3f447fa.dirty-py3.6.egg/datacube/storage/_load.py", line 71, in reproject_and_fuse
    with datasources[0].open() as rdr:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/datacube-1.7rc1+3.gd3f447fa.dirty-py3.6.egg/datacube/storage/_rio.py", line 201, in open
    raise e
  File "/usr/local/lib/python3.6/dist-packages/datacube-1.7rc1+3.gd3f447fa.dirty-py3.6.egg/datacube/storage/_rio.py", line 167, in open
    with rasterio.open(self.filename, sharing=False) as src:
  File "/usr/local/lib/python3.6/dist-packages/rasterio/env.py", line 423, in wrapper
    return f(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/rasterio/__init__.py", line 216, in open
    s = DatasetReader(path, driver=driver, **kwargs)
  File "rasterio/_base.pyx", line 215, in rasterio._base.DatasetBase.__init__
rasterio.errors.RasterioIOError: netCDF:"/home/nikola/Data/SULAMOSA/SD022_sbas_short.nc":None: No such file or directory
```

**Comment by Kirill888** [comment]
@jankovicgd for netcdf files `layer`  parameter in the dataset definition must refer to the variable name inside netcdf file, I guess it should be `layer: deformation_up_down` in your case, but you have `layer: 1`, the fact that `dc.load` attempts to load a variable named `None` instead of reporting  an error is obviously a problem that should be fixed, I'll make a separate issue for that.

**Comment by jankovicgd** [comment]
Thanks for the help @Kirill888, this has worked! Maybe also an update to the documentation since I only understood that `layer` parameter represents the order of layers in the dataset. You may close this.
