### ISSUE TITLE
NCI VDI pgpass issue

### ISSUE THREAD

**Issue by benwah92** [opendatacube/datacube-core#859]
### Expected behaviour
I am trying to connect to DEA running the sh /g/data/v10/public/digitalearthau/install.sh as described in https://docs.dea.ga.gov.au/setup/NCI/install.html. I would expect that this loads up everything (including reading the pgpass file) to access the postgres database etc with the final output being jupyter-labs up and running with working DEA modules.

### Actual behaviour
At some point, I have created an account. There is an issue reading my pgpass file. When I double click the DEA icon on my desktop, I get the following errors in terminal:

Traceback (most recent call last):
  File "/g/data/v10/public/modules/dea/20191127/bin/datacube-ensure-user.py", line 202, in <module>
    main()
  File "/g/data/v10/public/modules/dea-env/20191127/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/g/data/v10/public/modules/dea-env/20191127/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/g/data/v10/public/modules/dea-env/20191127/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/g/data/v10/public/modules/dea-env/20191127/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/g/data/v10/public/modules/dea/20191127/bin/datacube-ensure-user.py", line 139, in main
    new_creds = find_credentials(pgpass, OLD_DB_HOST, dbcreds)
  File "/g/data/v10/public/modules/dea/20191127/bin/datacube-ensure-user.py", line 83, in find_credentials
    creds = DBCreds(*line.strip().split(':'))
TypeError: __new__() missing 4 required positional arguments: 'port', 'database', 'username', and 'password'
Error: database connection check failed!
  see log above for more details

### Steps to reproduce the behaviour
Double clicking the DEA icon reproduces this error. 

### Environment information
I ran the sh /g/data/v10/public/digitalearthau/install.sh as described above which loads the dea module. This is being done in the VDI environment.

**Comment by omad** [comment]
Hi yobimania,

Can you please message me on [ODC Slack](http://slack.opendatacube.org/) @omad. This is more of a DEA/NCI specific problem than something to do with ODC itself.

I'll close this here and we'll sort it out together please.
Damien
