### ISSUE TITLE
psycopg2 cannot connect to datacube

### ISSUE THREAD

**Issue by Massetting** [opendatacube/datacube-core#866]
Hello datacubers, 

I am forwarding this problem I already posted on the datacube slack last week.
I have been trying to update gdal to a version that supports bigtiff. Unfortunately, with the newly updated packages, the PostgreSQL connection attempted by the datacube keeps failing due to a psycopg2 error. It seems though that it is related to a Postgres bug. 
Is there a quick fix in psycopg2 configuration (in the datacube) to allow me to connect to my datacube?
Thanks 
Andrea

### Expected behaviour
```
dc = datacube.Datacube(app='test')
_Connects_
```

### Actual behaviour

```
dc = datacube.Datacube(app='test')
Traceback (most recent call last):

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\engine\base.py", line 2276, in _wrap_pool_connect
    return fn()

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\pool\base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\pool\base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\pool\impl.py", line 139, in _do_get
    self._dec_overflow()

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\pool\impl.py", line 136, in _do_get
    return self._create_connection()

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\pool\base.py", line 652, in __connect
    connection = pool._invoke_creator(self)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\engine\default.py", line 489, in connect
    return self.dbapi.connect(*cargs, **cparams)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\psycopg2\__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)

OperationalError: FATAL:  unsupported frontend protocol 1234.5679: server supports 2.0 to 3.0



The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-29-457a71ba855f>", line 1, in <module>
    dc = datacube.Datacube(app='test')

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\datacube\api\core.py", line 81, in __init__
    validate_connection=validate_connection)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\datacube\index\_api.py", line 43, in index_connect
    validate_connection=validate_connection)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\datacube\index\index.py", line 93, in connect_to_index
    return Index.from_config(config, application_name, validate_connection)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\datacube\index\index.py", line 52, in from_config
    validate_connection=validate_connection)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\datacube\drivers\postgres\_connections.py", line 74, in from_config
    pool_timeout=int(config.get('db_connection_timeout', 60))

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\datacube\drivers\postgres\_connections.py", line 89, in create
    if not _core.database_exists(engine):

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\datacube\drivers\postgres\_core.py", line 117, in database_exists
    return has_schema(engine, engine)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\datacube\drivers\postgres\_core.py", line 218, in has_schema
    return engine.dialect.has_schema(connection, SCHEMA_NAME)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\dialects\postgresql\base.py", line 2575, in has_schema
    type_=sqltypes.Unicode,

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\engine\base.py", line 2181, in execute
    connection = self._contextual_connect(close_with_result=True)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\engine\base.py", line 2242, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\engine\base.py", line 2280, in _wrap_pool_connect
    e, dialect, self

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\engine\base.py", line 1547, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\engine\base.py", line 2276, in _wrap_pool_connect
    return fn()

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\pool\base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\pool\base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\pool\impl.py", line 139, in _do_get
    self._dec_overflow()

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\pool\impl.py", line 136, in _do_get
    return self._create_connection()

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\pool\base.py", line 652, in __connect
    connection = pool._invoke_creator(self)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\sqlalchemy\engine\default.py", line 489, in connect
    return self.dbapi.connect(*cargs, **cparams)

  File "C:\Users\Massetti\.conda\envs\testgdal\lib\site-packages\psycopg2\__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)

OperationalError: (psycopg2.OperationalError) FATAL:  unsupported frontend protocol 1234.5679: server supports 2.0 to 3.0

(Background on this error at: http://sqlalche.me/e/e3q8)
```

### Steps to reproduce the behaviour on Win64

From Anaconda command line:

    conda create -n testgdal -c conda-forge gdal datacube fiona vs2015_runtime=14
    [...]
    conda activate testgdal
    python
    >>>import datacube
    >>>dc = datacube.Datacube(app='test')

### Environment information

```
Packages in environment at C:\Users\Massetti\.conda\envs\testgdal:

Name                    Version                   Build  Channel
affine                    2.3.0                      py_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
amqp                      2.5.2                      py_0    conda-forge
argh                      0.26.2                py36_1001    conda-forge
astroid                   2.3.3                    py36_1    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
autopep8                  1.5                        py_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bcrypt                    3.1.7            py36hfa6e2cd_0    conda-forge
billiard                  3.6.0.0          py36hfa6e2cd_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bokeh                     1.4.0                    py36_0    conda-forge
boost-cpp                 1.70.0               h6a4c333_2    conda-forge
bzip2                     1.0.8                hfa6e2cd_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cachetools                3.1.1                      py_0    conda-forge
celery                    4.4.0                      py_0    conda-forge
certifi                   2019.11.28               py36_0    conda-forge
cffi                      1.13.2           py36hb32ad35_0    conda-forge
cfitsio                   3.470                hfa6e2cd_2    conda-forge
cftime                    1.0.4.2          py36hc8d92b1_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
colorama                  0.4.3                      py_0    conda-forge
cryptography              2.8              py36hb32ad35_1    conda-forge
curl                      7.68.0               h4496350_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py36hfa6e2cd_0    conda-forge
dask                      2.10.1                     py_0    conda-forge
dask-core                 2.10.1                     py_0    conda-forge
*datacube*                  *1.7*                        *py_1*    *conda-forge*
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
diff-match-patch          20181111                   py_0    conda-forge
distributed               2.10.0                     py_0    conda-forge
docutils                  0.16                     py36_0    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
expat                     2.2.9                he025d50_2    conda-forge
fiona                     1.8.13           py36hb7fdc2d_0    conda-forge
flake8                    3.7.9                    py36_0    conda-forge
freetype                  2.10.0               h563cfd7_1    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
fsspec                    0.6.2                      py_0    conda-forge
future                    0.18.2                   py36_0    conda-forge
*gdal*                      *3.0.4*           *py36h2fee047_0*    *conda-forge*
geos                      3.8.0                he025d50_0    conda-forge
geotiff                   1.5.1                h9633a31_8    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.58.3          py36hc0c2ac7_1002    conda-forge
hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
hdf5                      1.10.5          nompi_ha405e13_1104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       64.2                 he025d50_1    conda-forge
idna                      2.8                   py36_1000    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib_metadata        1.5.0                    py36_0    conda-forge
intel-openmp              2020.0                      166
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.1.4            py36h5ca1d4c_0    conda-forge
ipython                   7.12.0           py36h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     4.3.21                   py36_0    conda-forge
jedi                      0.14.1                   py36_0    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                3.2.0                    py36_0    conda-forge
jupyter_client            5.3.4                    py36_1    conda-forge
jupyter_core              4.6.1                    py36_0    conda-forge
kealib                    1.4.10            hf7dc31f_1005    conda-forge
keyring                   21.1.0                   py36_0    conda-forge
kiwisolver                1.1.0            py36he980bc4_0    conda-forge
kombu                     4.6.7                    py36_1    conda-forge
krb5                      1.16.4               hdd46e55_0    conda-forge
lazy-object-proxy         1.4.3            py36hfa6e2cd_1    conda-forge
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
libcurl                   7.68.0               h4496350_0    conda-forge
libffi                    3.2.1             h6538335_1006    conda-forge
*libgdal*                   *3.0.4*                *h90de84b_0*   *conda-forge*
libiconv                  1.15              hfa6e2cd_1005    conda-forge
libkml                    1.3.0             h4ece8bf_1010    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
libnetcdf                 4.7.3           nompi_hc957ea6_101    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libpq                     12.1                 hb0bdaea_0    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
libspatialindex           1.9.3                he025d50_1    conda-forge
libspatialite             4.3.0a            hd027ac7_1034    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.1.0                h21b02b4_3    conda-forge
libwebp                   1.0.2                hfa6e2cd_5    conda-forge
libxml2                   2.9.10               h9ce36c8_0    conda-forge
libxslt                   1.1.33               heafd4d3_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.5.0            py36heafd4d3_0    conda-forge
lz4-c                     1.8.3             he025d50_1001    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
markupsafe                1.1.1            py36hfa6e2cd_0    conda-forge
matplotlib                3.1.3                    py36_0    conda-forge
matplotlib-base           3.1.3            py36h2981e6d_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py36hfa6e2cd_1000    conda-forge
mkl                       2019.4                      245
msgpack-python            0.6.2            py36he980bc4_0    conda-forge
msys2-conda-epoch         20160418                      1
munch                     2.5.0                      py_0    conda-forge
nbconvert                 5.6.1                    py36_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
*netcdf4*                   1.5.3           nompi_py36h0154fc0_102    conda-forge
numpy                     1.18.1           py36hc71023c_0    conda-forge
numpydoc                  0.9.2                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openssl                   1.1.1d               hfa6e2cd_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.1            py36he350917_0    conda-forge
pandoc                    2.9.1.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.1                    py36_0    conda-forge
parso                     0.6.1                      py_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pathtools                 0.1.2                      py_1    conda-forge
pcre                      8.43                 h6538335_0    conda-forge
pexpect                   4.8.0                    py36_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    7.0.0            py36h9ea1dd6_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
poppler                   0.67.0               h1707e21_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.1                 h06f7779_0    conda-forge
proj                      6.3.0                ha7a8c7b_0    conda-forge
prompt_toolkit            3.0.3                      py_0    conda-forge
psutil                    5.6.7            py36hfa6e2cd_0    conda-forge
*psycopg2*                  *2.8.4*            *py36hb32ad35_1*    *conda-forge*
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pydocstyle                5.0.2                      py_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pylint                    2.4.4                    py36_0    conda-forge
pynacl                    1.3.0           py36h2fa13f4_1001    conda-forge
pyodbc                    4.0.28           py36h6538335_0    conda-forge
pyopenssl                 19.1.0                   py36_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pypeg2                    2.15.2                   py36_0    conda-forge
pyqt                      5.12.3           py36h6538335_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.7           py36hfa6e2cd_0    conda-forge
pysocks                   1.7.1                    py36_0    conda-forge
python                    3.6.7             he025d50_1006    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.3.4                      py_0    conda-forge
python-language-server    0.31.7                   py36_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywin32                   225              py36hfa6e2cd_0    conda-forge
pywin32-ctypes            0.2.0                 py36_1000    conda-forge
pyyaml                    5.3              py36hfa6e2cd_0    conda-forge
pyzmq                     18.1.1           py36h16f9016_0    conda-forge
qdarkstyle                2.8                        py_0    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtawesome                 0.6.1                      py_0    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
rasterio                  1.1.0            py36h039b02d_0
redis-py                  3.4.1                      py_0    conda-forge
requests                  2.22.0                   py36_1    conda-forge
rope                      0.16.0                     py_0    conda-forge
rtree                     0.9.3            py36hbf79ddb_0    conda-forge
setuptools                45.2.0                   py36_0    conda-forge
shapely                   1.7.0            py36h2130f3d_0    conda-forge
singledispatch            3.4.0.3               py36_1000    conda-forge
six                       1.14.0                   py36_0    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sphinx                    2.3.1                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
spyder                    4.0.1                    py36_0    conda-forge
spyder-kernels            1.8.1                    py36_1    conda-forge
*sqlalchemy*                *1.3.13*           *py36hfa6e2cd_0*    *conda-forge*
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
sshtunnel                 0.1.5                         0    conda-forge
tbb                       2018.0.5             he980bc4_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tiledb                    1.7.0                hffbbd95_2    conda-forge
tk                        8.6.10               hfa6e2cd_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py36hfa6e2cd_2    conda-forge
tqdm                      4.42.1                     py_0    conda-forge
traitlets                 4.3.3                    py36_0    conda-forge
typed-ast                 1.4.1            py36hfa6e2cd_0    conda-forge
ujson                     1.35            py36hfa6e2cd_1001    conda-forge
urllib3                   1.25.7                   py36_0    conda-forge
vc                        14.1                 h0510ff6_4
vine                      1.3.0                      py_0    conda-forge
vs2015_runtime            14.16.27012          hf0eaf9b_1
watchdog                  0.10.2                   py36_0    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
win_inet_pton             1.1.0                    py36_0    conda-forge
wincertstore              0.2                   py36_1003    conda-forge
wrapt                     1.11.2           py36hfa6e2cd_0    conda-forge
xarray                    0.15.0                     py_0    conda-forge
xerces-c                  3.2.2             h6538335_1004    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
yaml                      0.2.2                hfa6e2cd_1    conda-forge
yapf                      0.28.0                     py_0    conda-forge
zeromq                    4.3.2                h6538335_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zipp                      2.2.0                      py_0    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
zstd                      1.4.4                hd8a0e53_1    conda-forge
```

**Comment by Massetting** [comment]
Note: when I change the psycopg2 build to the one that was working fine, I need to change channel:

    conda install psycopg2=2.8.3=py36h7a1dbc1_0


This results in:

```
The following packages will be SUPERSEDED by a higher-priority channel:

  certifi                                       conda-forge --> pkgs/main
  gdal               conda-forge::gdal-3.0.4-py36h2fee047_0 --> pkgs/main::gdal-3.0.2-py36hdf43c64_0
  geotiff             conda-forge::geotiff-1.5.1-h9633a31_8 --> pkgs/main::geotiff-1.5.1-h5770a2b_0
  hdf5               conda-forge::hdf5-1.10.5-nompi_ha405e~ --> pkgs/main::hdf5-1.10.4-h7ebc959_0
  icu                      conda-forge::icu-64.2-he025d50_1 --> pkgs/main::icu-58.2-ha66f8fd_1
  kealib             conda-forge::kealib-1.4.10-hf7dc31f_1~ --> pkgs/main::kealib-1.4.7-h07cbb95_6
  libgdal             conda-forge::libgdal-3.0.4-h90de84b_0 --> pkgs/main::libgdal-3.0.2-h1155b67_0
  libnetcdf          conda-forge::libnetcdf-4.7.3-nompi_hc~ --> pkgs/main::libnetcdf-4.6.1-h411e497_2
  libpq                  conda-forge::libpq-12.1-hb0bdaea_0 --> pkgs/main::libpq-11.2-h3235a2c_0
  libspatialite      conda-forge::libspatialite-4.3.0a-hd0~ --> pkgs/main::libspatialite-4.3.0a-h7ffb84d_0
  libtiff             conda-forge::libtiff-4.1.0-h21b02b4_3 --> pkgs/main::libtiff-4.1.0-h56a325e_0
  netcdf4            conda-forge::netcdf4-1.5.3-nompi_py36~ --> pkgs/main::netcdf4-1.4.2-py36h812ae01_0
  postgresql         conda-forge::postgresql-12.1-h06f7779~ --> pkgs/main::postgresql-11.2-h3235a2c_0
  proj                   conda-forge::proj-6.3.0-ha7a8c7b_0 --> pkgs/main::proj-6.2.1-h9f7ef89_0
  psycopg2           conda-forge::psycopg2-2.8.4-py36hb32a~ --> pkgs/main::psycopg2-2.8.3-py36h7a1dbc1_0
  pyqt               conda-forge::pyqt-5.12.3-py36h6538335~ --> pkgs/main::pyqt-5.9.2-py36h6538335_2
  qt                      conda-forge::qt-5.12.5-h7ef1ec2_0 --> pkgs/main::qt-5.9.7-vc14h73c81de_0
  tiledb               conda-forge::tiledb-1.7.0-hffbbd95_2 --> pkgs/main::tiledb-1.6.3-h7b000aa_0
  zstd                   conda-forge::zstd-1.4.4-hd8a0e53_1 --> pkgs/main::zstd-1.3.7-h508b16e_0
```

Now I am able to connect to postgres with `datacube.Datacube()` [i.e. no error] but every query done on dc.load() is now returning an empty xarray.....

**Comment by Massetting** [comment]
I finally got the datacube working again and able to handle bigtiff.

1. Standard install `gdal` and `datacube` [conda-forge] this install gdal 3.0.4 (connection to postgres not working) 
2. Downgrade psycopg2 to 2.8.3=py36h7a1dbc1_0 [main]; this downgrades gdal to 3.0.2 (no loads in dc probably due to broken rasterio dependency)
3. Upgrade rasterio to 1.1.2 [conda-forge], this downgrades gdal to 2.4.3 and all works again

Eventually the `gdal=2.4.3=py36he6b6c38_9 [conda-forge]` that replaced the `gdal=2.3.3=py36hdf43c64_0[main]` is now able to read bigtiff.

The last bit of conda installations to conclude what posted above:

```
conda install -c conda-forge rasterio=1.1.2

The following packages will be UPDATED:

  hdf5                    pkgs/main::hdf5-1.10.4-h7ebc959_0 --> conda-forge::hdf5-1.10.5-nompi_ha405e13_1104
  icu                        pkgs/main::icu-58.2-ha66f8fd_1 --> conda-forge::icu-64.2-he025d50_1
  kealib                 pkgs/main::kealib-1.4.7-h07cbb95_6 --> conda-forge::kealib-1.4.10-hf7dc31f_1005
  libnetcdf           pkgs/main::libnetcdf-4.6.1-h411e497_2 --> conda-forge::libnetcdf-4.7.1-nompi_he2c6080_102
  libpq                    pkgs/main::libpq-11.2-h3235a2c_0 --> conda-forge::libpq-11.5-hb0bdaea_2
  libspatialite      pkgs/main::libspatialite-4.3.0a-h7ffb~ --> conda-forge::libspatialite-4.3.0a-h2b2ca8d_1032
  netcdf4            pkgs/main::netcdf4-1.4.2-py36h812ae01~ --> conda-forge::netcdf4-1.5.3-nompi_py36h4f78263_101
  postgresql          pkgs/main::postgresql-11.2-h3235a2c_0 --> conda-forge::postgresql-11.5-h06f7779_2
  qt                     pkgs/main::qt-5.9.7-vc14h73c81de_0 --> conda-forge::qt-5.9.7-h506e8af_3
  rasterio           pkgs/main::rasterio-1.1.0-py36h039b02~ --> conda-forge::rasterio-1.1.2-py36h163c445_0

The following packages will be SUPERSEDED by a higher-priority channel:

  gdal                 pkgs/main::gdal-3.0.2-py36hdf43c64_0 --> conda-forge::gdal-2.4.3-py36he6b6c38_9
  libgdal               pkgs/main::libgdal-3.0.2-h1155b67_0 --> conda-forge::libgdal-2.4.3-h31cfd43_9

The following packages will be DOWNGRADED:

  fiona                               1.8.13-py36hb7fdc2d_0 --> 1.8.9.post2-py36h3234bc7_0
  geos                                     3.8.0-he025d50_0 --> 3.7.2-he025d50_2
  shapely                              1.7.0-py36h2130f3d_0 --> 1.6.4-py36ha35856d_1006
```

**Comment by Kirill888** [comment]
common dependency between `gdal` and `psycopg2` is `libpq`. Whether brokenness is in `libpq` or in the `psycopg2` is hard to say. With `gdal` depending on so many libs it's impossible to have broad coverage of all possible versions of libs it depends, so yeah downgrading to a last known good config is the only way. 

I had no issue with compiled `psycopg2==2.8.4` and `gdal==3.0.4` on linux, so my guess is that either more recent `libpq` is borked or conda build of it is broken. With conda being the way it is, even if `libpq` is fixed already you won't see a fix until `gdal` gets released again, at that point probably some other lib it depends on will be in a bad state.
